/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FoodTraceability } from "./FoodTraceability";
export * as factories from "./factories";
export { FoodTraceability__factory } from "./factories/FoodTraceability__factory";
